"""Build and write Obsidian-visible markdown sidecars."""

from __future__ import annotations

import os
from pathlib import Path
from typing import List

from . import __version__

# Each original gets its own per-file folder (sibling of the sidecar), so a note and
# its resources move together: `f.pdf` -> `.f.pdf-resources/f.pdf`.
RESOURCE_SUFFIX = "-resources"


def resource_dir_name(source: Path) -> str:
    """Per-file resource folder name: `.<name>-resources`."""
    return f".{source.name}{RESOURCE_SUFFIX}"


def resource_ref(source: Path) -> str:
    """Relative path (from the sidecar) to the original inside its resource folder."""
    return f"{resource_dir_name(source)}/{source.name}"


def build_markdown(source: Path, pages: List[str]) -> str:
    """Compose sidecar markdown for a source file given its OCR'd page texts.

    Images produce a single "page"; PDFs produce one per page.
    The original is referenced inside a per-file `.resource-<name>/` folder. Obsidian
    hides dot-folders, so a relative markdown link (angle-bracketed for spaces) is used
    rather than an `![[ ]]` embed, which would not resolve from a hidden folder.
    """
    generated_by = f"obsidian-ocr {__version__}"
    ref = resource_ref(source)
    lines = [
        "---",
        f"source: {ref}",
        f"generated_by: {generated_by}",
        f"pages: {len(pages)}",
        "---",
        "",
        f"> OCR transcript of `{source.name}` (generated by {generated_by}).",
        f"> Original: [{source.name}](<{ref}>)",
        "",
    ]

    if len(pages) == 1:
        lines.append(pages[0].strip())
    else:
        for index, text in enumerate(pages, start=1):
            lines.append(f"## Page {index}")
            lines.append("")
            lines.append(text.strip())
            lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def write_sidecar(sidecar: Path, content: str) -> None:
    """Atomically write `content` to `sidecar`."""
    tmp = sidecar.with_name(sidecar.name + ".tmp")
    tmp.write_text(content, encoding="utf-8")
    os.replace(tmp, sidecar)


def move_to_resource(source: Path) -> Path:
    """Move `source` into its own sibling `.<name>-resources/` folder; return new path."""
    dest_dir = source.parent / resource_dir_name(source)
    dest_dir.mkdir(exist_ok=True)
    dest = dest_dir / source.name
    os.replace(source, dest)
    return dest
