"""Build and write Obsidian-visible markdown sidecars.

Originals are left exactly where they are. For an image `a/b/f.png` we write a
sibling `a/b/f.png.md` that **embeds the image in place** (`![[f.png]]`); for a PDF
`a/b/f.pdf` we write `a/b/f.pdf.md` with the per-page OCR text and a markdown
**link** back to the original `f.pdf` (the PDF itself is never moved).
"""

from __future__ import annotations

import os
from pathlib import Path
from typing import List

from . import __version__

NO_TEXT_PLACEHOLDER = "_(no text detected)_"


def _generated_by() -> str:
    return f"obsidian-ocr {__version__}"


def build_image_markdown(source: Path, text: str) -> str:
    """Sidecar for an image: front matter, the embedded image, then its OCR text.

    Only called when OCR produced text — a text-less image gets no sidecar at all.
    The image stays in place, so it is embedded by its bare filename.
    """
    generated_by = _generated_by()
    return (
        "\n".join(
            [
                "---",
                f"source: {source.name}",
                f"generated_by: {generated_by}",
                "type: image",
                "---",
                "",
                f"> OCR transcript of `{source.name}` (generated by {generated_by}).",
                "",
                f"![[{source.name}]]",
                "",
                text.strip(),
            ]
        ).rstrip()
        + "\n"
    )


def build_pdf_markdown(source: Path, page_texts: List[str]) -> str:
    """Sidecar for a PDF: front matter, a link to the original, then per-page OCR text.

    The PDF is never moved, so it is linked by its bare filename. Pages with no
    detected text get a placeholder so the page numbering stays intact.
    """
    generated_by = _generated_by()
    lines = [
        "---",
        f"source: {source.name}",
        f"generated_by: {generated_by}",
        f"pages: {len(page_texts)}",
        "type: pdf",
        "---",
        "",
        f"> OCR transcript of `{source.name}` (generated by {generated_by}).",
        f"> Original: [{source.name}](<{source.name}>)",
        "",
    ]

    multipage = len(page_texts) > 1
    for index, text in enumerate(page_texts, start=1):
        if multipage:
            lines.append(f"## Page {index}")
            lines.append("")
        lines.append(text.strip() or NO_TEXT_PLACEHOLDER)
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def write_sidecar(sidecar: Path, content: str) -> None:
    """Atomically write `content` to `sidecar`."""
    tmp = sidecar.with_name(sidecar.name + ".tmp")
    tmp.write_text(content, encoding="utf-8")
    os.replace(tmp, sidecar)


def notext_marker_path(source: Path) -> Path:
    """Hidden marker recording that `source` was OCR'd and had no usable text.

    `a/b/f.png` -> `a/b/.f.png.notext`. Dot-prefixed so Obsidian hides it and the
    walker skips it; its presence lets re-runs skip re-OCRing a text-less image.
    """
    return source.with_name(f".{source.name}.notext")


def write_notext_marker(source: Path) -> None:
    """Create the empty `.notext` marker for `source` (idempotent)."""
    notext_marker_path(source).touch()
